### ISSUE TITLE
What can I do?

### ISSUE THREAD

**Issue by FlowingSPDG** [xNWP/HLAE-Server#1]
Hello. I'm Japanese CSGO Tournament manager.

I found this from HLAE's mirv_pgl command.
I've tested mirv_pgl_test from advancedfx and I succeed to show times,Cordinates,and Rotates.
But,I don't know what can I do with this.
Please teach me.

Sorry if I'm rude.
Thanks.

**Comment by xNWP** [comment]
Hi ruk1ium, this is a relatively simple CLR .net library meant to ease the use of hosting a server for mirv_pgl. For the use in tournaments you could write a simple app with this program to transmit player/camera positions, times, rotations, etc. to external compositing equipment/software. The obvious use for the mirv_pgl functionality is to map 3D elements live into a match, i.e. think how american football games project first down lines onto the screen live during games. You could do something similar to this. Regardless of how you use the information you can gather from mirv_pgl you can look at the example code on how to simply get that data into a variable, and sent off wherever you'd need. Keep in mind that if you wanted to match 3d elements live onto gameplay you'll need to use the time feature along with mirv_pgl draw to match these up as there will be some delay. This is all very advanced stuff but is definitely doable, and something that pgl is looking into (hence the name mirv_pgl).

**Comment by FlowingSPDG** [comment]
Thanks for replying! This is actually awesome.
My question is solved, I'll try this for my tournament.
Thanks so much!

**Comment by dtugend** [comment]
@ruk1ium 
https://github.com/advancedfx/advancedfx/tree/master/misc/mirv_pgl_test
https://github.com/advancedfx/advancedfx/tree/master/misc/MirvPglDrawTest

**Comment by FlowingSPDG** [comment]
@dtugend Thx for reply.
yeah I tested mirv_pgl_test already and i knew it can receive time/cordinates/rotates.
and what MirvPglDrawTest can do? May I know?

**Comment by dtugend** [comment]
mirv_pgl draw encodes the
client time,
camera position, rotation, fov

Into a code on the screen.

MirvPglDrawTest is for decoding that.

Depending on your set-up you might want to lower the bits stuffed into a pixel color chanel to i.e. 1 (default is 6).

**Comment by FlowingSPDG** [comment]
I guess I have understood how to use mirv_pgl,at my reposistory.
Thanks a lot!

**Comment by xNWP** [comment]
Glad to hear! :)
